---
title: "MT: Non-concurrent comparisons in platform trials - preliminary simulations"
author: 
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: true
    number_sections: true
    code_folding: show 
    theme: flatly
---

```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(collapse = TRUE,
               comment = "#>",
               warning = FALSE,
               message = FALSE,
               fig.align = "center",
               out.width = "70%")
```

```{r, warning=FALSE, message=FALSE, include=FALSE}
library(tidyverse)
library(kableExtra)
library(latex2exp)
library(NCC)
set.seed(717)
```

# Scenario I

- 2 treament arms
- $n=3000$
- $d=(0, 2000)$
- $\theta_1=0.25$; $\theta_2=0$
- equal time trend - linear and stepwise


Sample sizes - overview by period:

```{r}
get_ss_matrix(num_arms = 2, n_arm = 3000, d = c(0,2000))
```




```{r, include=FALSE}
results_i_alpha <- read_csv("results/results_i_alpha.csv")
```

```{r, echo=FALSE}
ggplot(results_i_alpha) +
  geom_line(aes(lambda1, reject_h0, color=model)) +
  geom_point(aes(lambda1, reject_h0, color=model)) +
  labs(x=TeX("$\\lambda$"), y="Type I error", color="Analysis approach:") +
  geom_hline(aes(yintercept = 0.1), linetype = "dotted") +
  facet_grid(~ trend) +
  scale_color_discrete(labels = c("Fixed effects model", "Mixed effects model", "Pooled analysis", "Separate analysis"))
```

