---
title: "Model-based approaches for modeling response over time in the presence of time trends"
uthor: "Pavla Krotka, Marta Bofill Roig"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: true
    number_sections: true
    code_folding: show 
    theme: flatly  
    includes:
      after_body: footer.html
---

```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(collapse = TRUE,
               echo = FALSE,
               comment = "#>",
               warning = FALSE,
               message = FALSE,
               fig.align = "center",
               out.width = "100%")

htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

```{r}
library(tidyverse)
library(ggpubr)
library(kableExtra)
library(latex2exp)

library(NCC)
library(np)
library(mgcv)
library(splines)
library(lmerTest)
```


# Methods

- Fixed-effect model with stepwise (period) adjustment
- Fixed-effect model with linear adjustment
- Mixed-effect model with stepwise (period) adjustment
- Local regression (LOESS)
- Generalized additive model with P-splines
- Kernel regression

# Fitted values - linear trend

```{r}
data_lin <- datasim_cont(num_arms = 3, n_arm = 100, d = c(0, 100, 250),
                         theta = rep(0, 3), lambda = rep(5, 4), sigma = 1, trend = "linear", full=T)$Data

data_lin$treatment <- as.factor(data_lin$treatment)
data_lin$period <- as.factor(data_lin$period)
```

```{r, include=FALSE}
fix_step <- lm(response ~ treatment + period, data_lin)
fix_lin <- lm(response ~ treatment + j, data_lin)

mix_step <- lmer(response ~ treatment + (1 | period), data_lin)

gam <- gam(
  response ~ treatment + s(j, bs = "cr", k = 10), 
  data = data_lin, 
  method = "REML"
)

kernel <- npregbw(formula = response ~ treatment + j,
                  data = data_lin)
```

```{r, fig.height=8, fig.width=8}
ggarrange(ggplot(data_lin) + 
            aes(x = j, y = response, color = treatment) + 
            geom_point(alpha = 0.5) + 
            geom_line(aes(y = fitted(fix_step)), size=1) +
            labs(x = "Patient recruitment", y = "Response", title = "Fixed-effect model with stepwise adjustment", color = "Treatment:"),
          
          ggplot(data_lin) + 
            aes(x = j, y = response, color = treatment) + 
            geom_point(alpha = 0.5) + 
            geom_line(aes(y = fitted(fix_lin)), size=1) +
            labs(x = "Patient recruitment", y = "Response", title = "Fixed-effect model with linear adjustment", color = "Treatment:"),
          
          ggplot(data_lin) + 
            aes(x = j, y = response, color = treatment) + 
            geom_point(alpha = 0.5) + 
            geom_line(aes(y = fitted(mix_step)), size=1) +
            labs(x = "Patient recruitment", y = "Response", title = "Mixed-effect model with stepwise adjustment", color = "Treatment:"),
          
          ggplot(data_lin) + 
            aes(x = j, y = response, color = treatment) + 
            geom_point(alpha = 0.5) + 
            geom_line(aes(y = fitted(gam)), size=1) +
            labs(x = "Patient recruitment", y = "Response", title = "Generalized additive model with P-splines", color = "Treatment:"),
          
          ggplot(data_lin) + 
            aes(x = j, y = response, color = treatment) + 
            geom_point(alpha = 0.5) + 
            geom_line(aes(y = fitted(npreg(kernel))), size=1) +
            labs(x = "Patient recruitment", y = "Response", title = "Kernel regression", color = "Treatment:"),
          
          common.legend = T, legend = "bottom", nrow = 3, ncol = 2)
```



# Fitted values - inverted-U trend



```{r}
data_inv <- datasim_cont(num_arms = 3, n_arm = 100, d = c(0, 100, 250),
                         theta = rep(0, 3), lambda = rep(5, 4), sigma = 1, trend = "inv_u", N_peak = 200, full=T)$Data

data_inv$treatment <- as.factor(data_inv$treatment)
data_inv$period <- as.factor(data_inv$period)
```

```{r, include=FALSE}
fix_step <- lm(response ~ treatment + period, data_inv)
fix_lin <- lm(response ~ treatment + j, data_inv)

mix_step <- lmer(response ~ treatment + (1 | period), data_inv)

gam <- gam(
  response ~ treatment + s(j, bs = "cr", k = 10), 
  data = data_inv, 
  method = "REML"
)

kernel <- npregbw(formula = response ~ treatment + j,
                  data = data_inv)
```

```{r, fig.height=8, fig.width=8}
ggarrange(ggplot(data_inv) + 
            aes(x = j, y = response, color = treatment) + 
            geom_point(alpha = 0.5) + 
            geom_line(aes(y = fitted(fix_step)), size=1) +
            labs(x = "Patient recruitment", y = "Response", title = "Fixed-effect model with stepwise adjustment", color = "Treatment:"),
          
          ggplot(data_inv) + 
            aes(x = j, y = response, color = treatment) + 
            geom_point(alpha = 0.5) + 
            geom_line(aes(y = fitted(fix_lin)), size=1) +
            labs(x = "Patient recruitment", y = "Response", title = "Fixed-effect model with linear adjustment", color = "Treatment:"),
          
          ggplot(data_inv) + 
            aes(x = j, y = response, color = treatment) + 
            geom_point(alpha = 0.5) + 
            geom_line(aes(y = fitted(mix_step)), size=1) +
            labs(x = "Patient recruitment", y = "Response", title = "Mixed-effect model with stepwise adjustment", color = "Treatment:"),
          
          ggplot(data_inv) + 
            aes(x = j, y = response, color = treatment) + 
            geom_point(alpha = 0.5) + 
            geom_line(aes(y = fitted(gam)), size=1) +
            labs(x = "Patient recruitment", y = "Response", title = "Generalized additive model with P-splines", color = "Treatment:"),
          
          ggplot(data_inv) + 
            aes(x = j, y = response, color = treatment) + 
            geom_point(alpha = 0.5) + 
            geom_line(aes(y = fitted(npreg(kernel))), size=1) +
            labs(x = "Patient recruitment", y = "Response", title = "Kernel regression", color = "Treatment:"),
          
          common.legend = T, legend = "bottom", nrow = 3, ncol = 2)
```




















